name: Build and Commit index.cjs

on:
  push:
    branches:
      - develop # Trigger only on pushes to the develop branch

permissions:
  contents: write # Ensure the workflow can push to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Run Build
        run: npm run build

      # Step 5: Commit and push the updated file (index.cjs only)
      - name: Commit and Push Changes as Current User
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add index.cjs
          git commit -m "chore: update index.cjs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
