name: Release Drafter

on:
  push:
    branches:
      - release/**

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
