name: Release Drafter

on:
  push:
    branches:
      # Draft a release for pre-releases or regular releases from release/ branches or main
      - release/**
      - main
    tags:
      # Finalize the release when a tag (e.g., v1.0.0 or v1.0.0-beta.2) is pushed
      - 'v*'

permissions:
  contents: write

jobs:
  draft_release:
    # Triggers when changes are pushed to release/** or main branches
    if: startsWith(github.ref, 'refs/heads/release/') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      # Write permission is required to create or update a GitHub release
      contents: write
    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finalize_release:
    # Triggers only when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      # Write permission is required to publish a release
      contents: write
    steps:
      - name: Publish Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
